const songData = [
  {
    title: "No Lie",
    artist: "Sean Paul ft. Dua Lipa",
    year: 2016,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063971/no_lie_u4xrlx.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063975/No_Lie_izryd8.mp3",
    genre: "Pop",
    language: "English",
    bgColor: "#431a33ff",
    lyricsBgColor: "#431a33ff",
    lyricsColor: "#eefa3bff",
    lyrics: [
  { time: 0.58, text: "Feel your eyes, they all over me" },
  { time: 4.20, text: "Don't be shy, take control of me" },
  { time: 6.72, text: "Get the vibe it's gonna be lit tonight" },
  { time: 10.43, text: "Baby girl yuh a carry ten ton a fatness gimme some a dat" },
  { time: 13.41, text: "Pink sweetie badness, look how she hot" },
  { time: 16.15, text: "She a black goddess, but tell her don't stop" },
  { time: 18.40, text: "It's a good piece of mentals under the cap" },
  { time: 20.52, text: "Hot piece of gear, mami love how you talk" },
  { time: 23.29, text: "Watching every step, I dip upon what you got" },
  { time: 25.57, text: "Stayin' in my brain, I'm 'membering all the touch?" },
  { time: 27.76, text: "And my aim is to give you this love" },
  { time: 29.64, text: "Hypnotic the way you move" },
  { time: 31.66, text: "Let me acknowledge the way you do" },
  { time: 34.16, text: "And I would not lie or play you" },
  { time: 36.63, text: "Beam me up like Scottie" },
  { time: 39.13, text: "It's so hypnotic, the way you move" },
  { time: 41.40, text: "That's why I wanted to get to you" },
  { time: 43.69, text: "And I would not lie, complain to you" },
  { time: 45.88, text: "Pull so hypnotic" },
  { time: 47.64, text: "gyal we never miss" },
  { time: 48.94, text: "Feel your eyes, they all over me" },
  { time: 51.28, text: "Don't be shy, take control of me" },
  { time: 53.57, text: "Get the vibe, it's gonna be lit tonight" },
  { time: 56.68, text: "Gyal we never miss, gyal we never miss (no lie, no lie)" },
  { time: 58.67, text: "Hypnotized, pull another one" },
  { time: 60.56, text: "It's alright, I know what you want" },
  { time: 63.01, text: "Get the vibe, it's gonna be lit tonight" },
  { time: 64.82, text: "Gyal we never miss, gyal we never miss (no lie)" },
  { time: 68.29, text: "Feels how we do it (no lie)" },
  { time: 70.01, text: "It's always how we do it (no lie)" },
  { time: 72.51, text: "Feels how we do it" },
  { time: 73.54, text: "It's gonna be lit tonight (no lie)" },
  { time: 77.08, text: "Feels how we do it (no lie)" },
  { time: 79.35, text: "It's always how we do it (no lie)" },
  { time: 81.88, text: "Feels how we do it" },
  { time: 82.71, text: "It's gonna be lit tonight (no lie)" },
  { time: 86.55, text: "I'm so lit, so lit, my girl" },
  { time: 88.27, text: "So let me see you roll it, roll it, my girl" },
  { time: 90.72, text: "I love it when you bend and fold it, now let me bone it" },
  { time: 93.48, text: "And let me own it, my girl" },
  { time: 95.72, text: "Give you all the style that I have mustered" },
  { time: 97.97, text: "I say what, baby girl, that's my word" },
  { time: 100.04, text: "Give you the good lovin' that is preferred" },
  { time: 102.51, text: "You deserve it, so don't be scared" },
  { time: 105.15, text: "It's hypnotic, the way you move" },
  { time: 107.02, text: "Let me acknowledge the way you do" },
  { time: 109.48, text: "And I would not lie or play you" },
  { time: 111.82, text: "Beam me up like Scottie" },
  { time: 113.89, text: "It's so hypnotic, the way you move" },
  { time: 116.41, text: "That's why I wanted to get to you" },
  { time: 118.66, text: "And I would not lie, complain to you" },
  { time: 121.43, text: "Pull so hypnotic" },
  { time: 123.01, text: "gyal we never miss" },
  { time: 124.11, text: "Feel your eyes, they all over me" },
  { time: 126.61, text: "Don't be shy, take control of me" },
  { time: 128.90, text: "Get the vibe, it's gonna be lit tonight" },
  { time: 130.67, text: "Gyal we never miss, gyal we never miss (no lie)" },
  { time: 133.61, text: "Hypnotized, pull another one" },
  { time: 136.11, text: "It's alright, I know what you want" },
  { time: 138.36, text: "Get the vibe, it's gonna be lit tonight" },
  { time: 141.36, text: "Gyal we never miss, gyal we never miss (no lie)" },
  { time: 143.12, text: "Feels how we do it (no lie)" },
  { time: 145.01, text: "It's always how we do it (no lie)" },
  { time: 147.78, text: "Feels how we do it" },
  { time: 148.85, text: "It's gonna be lit tonight (no lie)" },
  { time: 152.84, text: "Feels how we do it (no lie)" },
  { time: 154.60, text: "It's always how we do it (no lie)" },
  { time: 156.89, text: "Feels how we do it" },
  { time: 158.11, text: "It's gonna be lit tonight (no lie)" },
  { time: 161.74, text: "Shake that body, let me see you just do it" },
  { time: 164.18, text: "Girl hundred percent (no lie)" },
  { time: 166.61, text: "Move that body, let me see you just do it" },
  { time: 168.91, text: "Girl go on represent (no lie)" },
  { time: 171.04, text: "Shake that body, let me see you just do it" },
  { time: 173.27, text: "To the fullest extent (no lie)" },
  { time: 175.89, text: "Move that body, let me see you just do it" },
  { time: 177.92, text: "Girl, you're magnificent (no lie)" },
  { time: 180.66, text: "Feel your eyes, they're all over me" },
  { time: 183.19, text: "Don't be shy, take control of me" },
  { time: 185.29, text: "Get the vibe, it's gonna be lit tonight" },
  { time: 188.36, text: "Gyal we never miss, gyal we never miss (no lie)" },
  { time: 190.11, text: "Hypnotized, pull another one" },
  { time: 192.40, text: "It's alright, I know what you want" },
  { time: 194.74, text: "Get the vibe, it's gonna be lit tonight" },
  { time: 198.05, text: "Gyal we never miss, gyal we never miss (no lie)" },
  { time: 199.49, text: "Feels how we do it (no lie)" },
  { time: 201.76, text: "It's always how we do it (no lie)" },
  { time: 203.99, text: "Feels how we do it" },
  { time: 205.44, text: "It's gonna be lit tonight (no lie)" },
  { time: 208.86, text: "Feels how we do it (no lie)" },
  { time: 211.03, text: "It's always how we do it (no lie)" },
  { time: 213.55, text: "Feels how we do it" },
  { time: 214.65, text: "It's gonna be lit tonight (no lie)" }
]

  },
  {
    title: "Arcade",
    artist: "Duncan Laurence",
    year: 2019,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063964/arcade_wrve1x.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063967/Arcade_ihj3j0.mp3",
    genre: "Pop",
    language: "English",
    bgColor: "#1F2B38",
    "lyricsBgColor": "#2A3545",
    "lyricsColor": "#33CFFF",
    lyrics: [
  { time: 13.45, text: "A broken heart is all that's left" },
  { time: 18.71, text: "I'm still fixing all the cracks" },
  { time: 23.49, text: "Lost a couple of pieces when" },
  { time: 28.03, text: "I carried it carried it carried it home" },
  { time: 33.61, text: "I'm afraid of all I am" },
  { time: 38.29, text: "My mind feels like a foreign land" },
  { time: 43.48, text: "Silence ringing inside my head" },
  { time: 48.24, text: "Please carry me carry me carry me home" },
  { time: 53.58, text: "I've spent all of the love I saved" },
  { time: 57.23, text: "We were always a losing game" },
  { time: 60.22, text: "Small-town boy in a big arcade" },
  { time: 63.78, text: "I got addicted to a losing game" },
  { time: 66.77, text: "Oh-oh-oh-oh oh-oh-oh-oh" },
  { time: 72.84, text: "All I know all I know" },
  { time: 76.92, text: "Loving you is a losing game" },
  { time: 81.94, text: "How many pennies in the slot" },
  { time: 86.74, text: "Giving us up didn't take a lot" },
  { time: 91.92, text: "I saw the end 'fore it begun" },
  { time: 96.37, text: "Still I carried I carried I carry on" },
  { time: 101.90, text: "Oh-oh-oh-oh oh-oh-oh-oh" },
  { time: 107.97, text: "All I know all I know" },
  { time: 111.84, text: "Loving you is a losing game" },
  { time: 115.24, text: "Oh-oh-oh-oh oh-oh-oh-oh" },
  { time: 121.16, text: "All I know all I know" },
  { time: 125.23, text: "Loving you is a losing game" },
  { time: 129.41, text: "I don't need your games game over" },
  { time: 135.90, text: "Get me off this rollercoaster" },
  { time: 142.00, text: "Oh-oh-oh-oh oh-oh-oh-oh" },
  { time: 147.77, text: "All I know all I know" },
  { time: 151.86, text: "Loving you is a losing game" },
  { time: 155.15, text: "Oh-oh-oh-oh oh-oh-oh-oh" },
  { time: 161.22, text: "All I know all I know" },
  { time: 165.24, text: "Loving you is a losing game" }
]

  },
  {
    title: "Hips Don't Lie",
    artist: "Shakira ft. Wyclef Jean",
    year: 2005,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063964/hips_dont_lie_pwl1ps.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063967/Hips_dont_lie_b9jho0.mp3",
    genre: "Pop",
    language: "English",
    bgColor: "#241c1a",
    lyricsBgColor: "#2e2422",
    lyricsColor: "#fcb040",
    lyrics: [
  { time: 0.00, text: "Ladies up in here tonight" },
  { time: 1.80, text: "No fighting" },
  { time: 4.00, text: "We got the refugees up in here (no fighting)" },
  { time: 7.10, text: "No fighting" },
  { time: 8.30, text: "Shakira, Shakira" },
  { time: 9.40, text: "I never really knew that she could dance like this" },
  { time: 11.80, text: "She makes a man wants to speak Spanish" },
  { time: 14.30, text: "Como se llama (si)" },
  { time: 15.60, text: "Bonita (si)" },
  { time: 17.00, text: "Mi casa (Shakira Shakira), su casa" },
  { time: 19.30, text: "Oh baby when you talk like that" },
  { time: 21.70, text: "You make a woman go mad" },
  { time: 24.10, text: "So be wise (si) and keep on (si)" },
  { time: 26.80, text: "Reading the signs of my body (uno, dos, tres, cuatro)" },
  { time: 29.40, text: "And I'm on tonight you know my hips don't lie" },
  { time: 32.00, text: "And I'm starting to feel it's right" },
  { time: 33.90, text: "All the attraction, the tension" },
  { time: 36.30, text: "Don't you see baby, this is perfection" },
  { time: 38.80, text: "Hey Girl, I can see your body moving" },
  { time: 41.90, text: "And it's driving me crazy" },
  { time: 43.20, text: "And I didn't have the slightest idea" },
  { time: 46.60, text: "Until I saw you dancing" },
  { time: 48.00, text: "And when you walk up on the dance floor" },
  { time: 49.80, text: "Nobody cannot ignore" },
  { time: 50.70, text: "The way you move your body, girl (just move)" },
  { time: 52.90, text: "And everything so unexpected, the way you right and left it" },
  { time: 56.20, text: "So you can keep on shaking it" },
  { time: 57.40, text: "I never really knew that she could dance like this" },
  { time: 59.80, text: "She makes a man wants to speak Spanish" },
  { time: 62.30, text: "Como se llama (si)" },
  { time: 63.80, text: "Bonita (si)" },
  { time: 65.00, text: "Mi casa (Shakira Shakira), su casa" },
  { time: 67.40, text: "Oh baby when you talk like that" },
  { time: 69.70, text: "You make a woman go mad" },
  { time: 72.10, text: "So be wise (si) and keep on (si)" },
  { time: 74.70, text: "Reading the signs of my body (no fighting)" },
  { time: 77.20, text: "And I'm on tonight you know my hips don't lie (no fighting)" },
  { time: 80.10, text: "And I am starting to feel you boy" },
  { time: 81.80, text: "Come on let's go, real slow" },
  { time: 84.30, text: "Don't you see baby asi es perfecto" },
  { time: 86.80, text: "I know I am on tonight" },
  { time: 88.50, text: "My hips don't lie and I am starting to feel it's right" },
  { time: 91.50, text: "All the attraction, the tension" },
  { time: 93.80, text: "Don't you see baby, this is perfection (Shakira, Shakira)" },
  { time: 95.90, text: "Oh boy, I can see your body moving" },
  { time: 99.50, text: "Half animal, half man" },
  { time: 100.90, text: "I don't, don't really know what I'm doing" },
  { time: 104.20, text: "But you seem to have a plan" },
  { time: 105.50, text: "My will and self restraint" },
  { time: 108.20, text: "Have come to fail now, fail now" },
  { time: 110.40, text: "See, I am doing what I can, but I can't so you know" },
  { time: 112.90, text: "That's a bit too hard to explain" },
  { time: 115.50, text: "Baila en la calle de noche" },
  { time: 117.80, text: "Baila en la calle de día" },
  { time: 120.10, text: "Baila en la calle de noche" },
  { time: 122.60, text: "Baila en la calle de día" },
  { time: 124.70, text: "I never really knew that she could dance like this" },
  { time: 127.00, text: "She makes a man wants to speak Spanish" },
  { time: 129.60, text: "Como se llama (si)" },
  { time: 131.10, text: "Bonita (si)" },
  { time: 132.40, text: "Mi casa (Shakira Shakira), su casa" },
  { time: 134.30, text: "Oh baby when you talk like that" },
  { time: 136.90, text: "You know you got me hypnotized" },
  { time: 139.40, text: "So be wise and keep on" },
  { time: 141.90, text: "Reading the signs of my body" },
  { time: 144.10, text: "Señorita," },
  { time: 145.10, text: "Feel the conga, let me see you move like you come from Colombia" },
  { time: 156.10, text: "Mira en Barranquilla se baila así, say it!" },
  { time: 158.80, text: "En Barranquilla se baila así" },
  { time: 165.50, text: "Yeah, she's so hot every man's fantasy a refugee" },
  { time: 167.90, text: "Like me back with the Fugees from a 3rd world country" },
  { time: 170.30, text: "I go back like when Pac carried crates" },
  { time: 172.70, text: "For Humpty Humpty we need a whole club dizzy" },
  { time: 175.10, text: "Why the CIA wanna watch us? Colombians and Haitians" },
  { time: 178.00, text: "I ain't guilty, it's a musical transaction" },
  { time: 179.80, text: "No more do we snatch ropes" },
  { time: 182.20, text: "Refugees run the seas 'cause we own our own boats (no fighting)" },
  { time: 184.90, text: "I'm on tonight" },
  { time: 186.70, text: "My hips don't lie and I am starting to feel you boy" },
  { time: 189.80, text: "Come on let's go, real slow" },
  { time: 192.30, text: "Baby like this is perfecto (no fighting)" },
  { time: 194.80, text: "Oh, you know I am on tonight" },
  { time: 196.50, text: "My hips don't lie and I am starting to feel it's right" },
  { time: 199.40, text: "The attraction" },
  { time: 200.60, text: "The tension" },
  { time: 201.80, text: "Baby, like this is perfection" },
  { time: 206.20, text: "No fighting" },
  { time: 208.60, text: "No fighting" }
]

  },
  {
    title: "Perfect",
    artist: "Ed Sheeran",
    year: 2017,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063973/perfect_emzps1.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063974/Perfect_ojrigr.mp3",
    genre: "Pop",
    language: "English",
    lyricsColor: "#00d9ff",
    lyricsBgColor: "#3f3d3dff",
    bgColor: "#0a1f30",
    lyrics: [
  { "time": 3.16, "text": "I found a love for me" },
  { "time": 10.41, "text": "Darling just dive right in" },
  { "time": 13.91, "text": "And follow my lead" },
  { "time": 18.16, "text": "Well I found a girl beautiful and sweet" },
  { "time": 25.67, "text": "I never knew you were the someone waiting for me" },
  { "time": 32.16, "text": "'Cause we were just kids when we fell in love" },
  { "time": 36.92, "text": "Not knowing what it was" },
  { "time": 40.66, "text": "I will not give you up this time" },
  { "time": 48.16, "text": "But darling, just kiss me slow, your heart is all I own" },
  { "time": 55.92, "text": "And in your eyes you're holding mine" },
  { "time": 62.40, "text": "Baby, I'm dancing in the dark with you between my arms" },
  { "time": 73.41, "text": "Barefoot on the grass, listening to our favorite song" },
  { "time": 80.91, "text": "When you said you looked a mess, I whispered underneath my breath" },
  { "time": 87.92, "text": "But you heard it, darling, you look perfect tonight" },
  { "time": 101.40, "text": "Well I found a woman, stronger than anyone I know" },
  { "time": 108.91, "text": "She shares my dreams, I hope that someday I'll share her home" },
  { "time": 116.17, "text": "I found a love, to carry more than just my secrets" },
  { "time": 124.42, "text": "To carry love, to carry children of our own" },
  { "time": 130.92, "text": "We are still kids, but we're so in love" },
  { "time": 135.41, "text": "Fighting against all odds" },
  { "time": 139.15, "text": "I know we'll be alright this time" },
  { "time": 146.67, "text": "Darling, just hold my hand" },
  { "time": 150.40, "text": "Be my girl, I'll be your man" },
  { "time": 154.42, "text": "I see my future in your eyes" },
  { "time": 160.91, "text": "Baby, I'm dancing in the dark, with you between my arms" },
  { "time": 172.16, "text": "Barefoot on the grass, listening to our favorite song" },
  { "time": 179.17, "text": "When I saw you in that dress, looking so beautiful" },
  { "time": 185.40, "text": "I don't deserve this, darling, you look perfect tonight" },
  { "time": 206.66, "text": "Baby, I'm dancing in the dark, with you between my arms" },
  { "time": 217.68, "text": "Barefoot on the grass, listening to our favorite song" },
  { "time": 224.41, "text": "I have faith in what I see" },
  { "time": 227.91, "text": "Now I know I have met an angel in person" },
  { "time": 234.67, "text": "And she looks perfect" },
  { "time": 238.17, "text": "I don't deserve this" },
  { "time": 242.42, "text": "You look perfect tonight" }
]
  },
  {
    title: "Believer",
    artist: "Imagine Dragons",
    year: 2017,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063965/believer_mkrtem.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063967/Believer_xhesa4.mp3",
    genre: "Rock",
    language: "English",
    bgColor: "#1c1a1a",
    lyricsBgColor: "#292727",
    lyricsColor: "#ff6a00",
    lyrics: [
  { time: 7.774, text: "First things first" },
  { time: 9.188, text: "I'ma say all the words inside my head" },
  { time: 12.194, text: "I'm fired up and tired of" },
  { time: 14.453, text: "The way that things have been, oh-ooh" },
  { time: 18.074, text: "The way that things have been, oh-ooh" },
  { time: 22.885, text: "Second thing second" },
  { time: 24.701, text: "Don't you tell me what you think that I could be" },
  { time: 27.273, text: "I'm the one at the sail" },
  { time: 29.483, text: "I'm the master of my sea, oh-ooh" },
  { time: 33.466, text: "The master of my sea, oh-ooh" },
  { time: 38.149, text: "I was broken from a young age" },
  { time: 40.073, text: "Taking my sulkin' to the masses" },
  { time: 41.967, text: "Writing my poems for the few" },
  { time: 43.733, text: "That look at me, took to me, shook at me, feelin' me" },
  { time: 45.780, text: "Singing from heartache from the pain" },
  { time: 47.674, text: "Taking my message from the veins" },
  { time: 49.516, text: "Speaking my lesson from the brain" },
  { time: 51.438, text: "Seeing the beauty through the..." },
  { time: 54.695, text: "Pain! You made me a, you made me a" },
  { time: 57.533, text: "Believer, believer" },
  { time: 62.224, text: "Pain! You break me down and build me up" },
  { time: 65.363, text: "Believer, believer" },
  { time: 69.023, text: "Pain! Oh, let the bullets fly, oh, let them rain" },
  { time: 74.786, text: "My life, my love, my drive, it came from…" },
  { time: 77.611, text: "Pain! You made me a, you made me a" },
  { time: 80.602, text: "Believer, believer" },
  { time: 84.405, text: "Third things third" },
  { time: 86.039, text: "Send a prayer to the ones up above" },
  { time: 88.947, text: "All the hate that you've heard" },
  { time: 90.777, text: "Has turned your spirit to a dove, oh-ooh" },
  { time: 94.868, text: "Your spirit up above, oh-ooh" },
  { time: 99.505, text: "I was chokin' in the crowd" },
  { time: 101.362, text: "Building my rain up in the cloud" },
  { time: 103.269, text: "Falling like ashes to the ground" },
  { time: 105.197, text: "Hoping my feelings, they would drown" },
  { time: 107.368, text: "But they never did, ever lived, ebbin' and flowin'" },
  { time: 109.431, text: "Inhibited, limited 'til it broke open and rained down" },
  { time: 112.574, text: "It rained down, like…" },
  { time: 116.099, text: "Pain! You made me a, you made me a" },
  { time: 118.962, text: "Believer, believer" },
  { time: 123.866, text: "Pain! You break me down and build me up" },
  { time: 126.647, text: "Believer, believer" },
  { time: 130.448, text: "Pain! Oh, let the bullets fly, oh, let them rain" },
  { time: 136.070, text: "My life, my love, my drive, it came from…" },
  { time: 139.121, text: "Pain! You made me a, you made me a" },
  { time: 141.999, text: "Believer, believer" },
  { time: 145.873, text: "Last things last" },
  { time: 147.473, text: "By the grace of the fire and the flames" },
  { time: 150.324, text: "You're the face of the future" },
  { time: 152.539, text: "The blood in my veins, oh-ooh" },
  { time: 156.253, text: "The blood in my veins, oh-ooh" },
  { time: 160.996, text: "But they never did, ever lived, ebbin' and flowin'" },
  { time: 163.235, text: "Inhibited, limited 'til it broke open and rained down" },
  { time: 166.288, text: "It rained down, like…" },
  { time: 169.963, text: "Pain! You made me a, you made me a" },
  { time: 172.624, text: "Believer, believer" },
  { time: 177.612, text: "Pain! You break me down and build me up" },
  { time: 180.410, text: "Believer, believer" },
  { time: 184.307, text: "Pain! Oh, let the bullets fly, oh, let them rain" },
  { time: 189.773, text: "My life, my love, my drive, it came from…" },
  { time: 192.890, text: "Pain! You made me a, you made me a" },
  { time: 195.755, text: "Believer, believer" }
]

  },
  {
    title: "Sapphire",
    artist: "Ed Sheeran ft. Arijit Singh",
    year: 2025,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063975/sapphire_vlraam.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063977/Sapphire_os0b7o.mp3",
    genre: "Fusion",
    language: "English",
    bgColor: "#0a1f30",
    lyricsBgColor: "#0a1f30",
    lyricsColor: "#a667ff",
    lyrics: [
  { time: 2.56, text: "You're glowing" },
  { time: 5.21, text: "You colour and fracture the light" },
  { time: 8.40, text: "You can't help but shine" },
  { time: 12.38, text: "And I know that" },
  { time: 15.03, text: "You carry the world on your back" },
  { time: 18.49, text: "But look at you tonight" },
  { time: 22.74, text: "The lights, your face, your eyes" },
  { time: 26.46, text: "Exploding like fireworks in the sky" },
  { time: 32.30, text: "Sapphire" },
  { time: 33.10, text: "Touching on your body while you're pushing on me" },
  { time: 35.49, text: "Don't you end the party, I could do this all week" },
  { time: 37.88, text: "We'll be dancing till the morning, go to bed, we won't sleep" },
  { time: 40.54, text: "Cham-cham chamke sitare wargi (Sapphire)" },
  { time: 43.46, text: "Touching on your body while you're pushing on me" },
  { time: 45.58, text: "Don't you end the party, I could do this all week" },
  { time: 47.97, text: "We'll be dancin' till the morning, go to bed, we won't sleep" },
  { time: 50.63, text: "Cham-cham chamke sitare wargi" },
  { time: 53.82, text: "Look what we found, Karma reached out" },
  { time: 56.21, text: "Into our hearts and pulled us to our feet now" },
  { time: 58.86, text: "You know, the truth is we could disappear" },
  { time: 60.99, text: "Anywhere, as long as I got you there" },
  { time: 63.64, text: "When the sun dies, till the day shines" },
  { time: 66.03, text: "When I'm with you, there's not enough time" },
  { time: 68.69, text: "You are my spring flower, watching you bloom, wow" },
  { time: 71.08, text: "We are surrounded, but I can only see" },
  { time: 73.47, text: "The lights, your face, your eyes" },
  { time: 76.92, text: "Exploding like fireworks in the sky" },
  { time: 82.77, text: "Sapphire" },
  { time: 83.83, text: "Touching on your body while you're pushing on me" },
  { time: 85.96, text: "Don't you end the party, I could do this all week" },
  { time: 88.35, text: "We'll be dancin' till the morning, go to bed, we won't sleep" },
  { time: 91.00, text: "Cham-cham chamke sitare wargi (Sapphire)" },
  { time: 93.66, text: "Touching on your body while you're pushing on me" },
  { time: 96.05, text: "Don't you end the party, I could do this all week" },
  { time: 98.44, text: "We'll be dancin' till the morning, go to bed, we won't sleep" },
  { time: 101.10, text: "Cham-cham chamke sitare wargi (Sapphire)" },
  { time: 104.55, text: "Mahrooni do nain lubhaaye" },
  { time: 106.41, text: "Chaandni cham-cham chamkaaye (You're glowing)" },
  { time: 109.59, text: "Noor da mainu ghoont pilaaye" },
  { time: 111.99, text: "Jindadi ban jaaye" },
  { time: 113.32, text: "You're glowing (Ambraan di tu jhaalar paaye)" },
  { time: 116.24, text: "You colour and fracture the light (Badlan de Latha de suit banaaye)" },
  { time: 119.42, text: "Look at you tonight (Kirnaan nu rang-roop chadaye)" },
  { time: 123.67, text: "(Morni ban jaaye) Sapphire" },
  { time: 124.22, text: "Palkan uthaave te hanere ghatde" },
  { time: 126.60, text: "Unglaan'ch paake tu dhanak phirdi" },
  { time: 128.72, text: "Kivein Rabb ne do naina ute neelam jade?" },
  { time: 131.64, text: "Cham-cham chamke sitaare wargi (Sapphire)" },
  { time: 134.30, text: "Touching on your body while you're pushing on me" },
  { time: 136.69, text: "Don't you end the party, I could do this all week" },
  { time: 138.82, text: "We'll be dancing till the morning, go to bed, we won't sleep" },
  { time: 141.47, text: "Cham-cham chamke sitare wargi (Sapphire)" },
  { time: 144.39, text: "Touching on your body while you're pushing on me (The lights, your face, your eyes)" },
  { time: 146.79, text: "Don't you end the party, I could do this all week (Exploding)" },
  { time: 149.44, text: "We'll be dancing till the morning, go to bed, we won't sleep (Like fireworks in the sky)" },
  { time: 151.83, text: "Cham-cham chamke sitare wargi (Sapphire)" },
  { time: 154.49, text: "Touching on your body while you're pushing on me (The lights, your face, your eyes)" },
  { time: 157.15, text: "Don't you end the party, I could do this all week (Exploding)" },
  { time: 159.53, text: "We'll be dancing till the morning, go to bed, we won't sleep (Like fireworks in the sky)" },
  { time: 161.92, text: "Cham-cham chamke sitare wargi (Sapphire)" },
  { time: 164.85, text: "The lights, your face, your eyes" },
  { time: 168.03, text: "Exploding like fireworks in the sky" },
  { time: 173.88, text: "Sapphire" }
]

  },
  // Hindi
  {
    title: "Yeh Raaten Yeh Mausam",
    artist: "Kishore Kumar, Asha Bhosle",
    year: 1958,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063976/yeh_raatein_emkeqs.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063977/Yeh_Raaten_Yeh_Mausam_r7qd1w.mp3",
    genre: "Romantic",
    language: "Hindi",
    bgColor: "#2d202c",
    lyricsBgColor: "#372a36",
    lyricsColor: "#fddde6",
    lyrics:  [
  { time: 0, text: "Yeh raaten yeh mausam, nadee ka kinara, ye chanchal hawaa" },
  { time: 11, text: "Aa... aa..." },
  { time: 13, text: "Yeh raaten yeh mausam, nadee ka kinara, ye chanchal hawaa" },
  { time: 23, text: "Kahaa do dillon ne, ki milkar kabhi hum na honge jooda" },
  { time: 32, text: "Yeh raaten yeh mausam, nadee ka kinara, ye chanchal hawaa" },
  { time: 51, text: "Ye kya baat hai aaj ki chandani me" },
  { time: 59, text: "Ye kya baat hai aaj ki chandani me" },
  { time: 66, text: "Ke hum kho gaye pyar ki raagani me" },
  { time: 71, text: "Ye baahon mein baahen, ye behki nigaahe" },
  { time: 76, text: "Lo aane lagaa zindagi ka mazaa" },
  { time: 81, text: "Yeh raaten yeh mausam, nadee ka kinara, ye chanchal hawaa" },
  { time: 96, text: "Sitaaron ki mehfil ne karke ishaara" },
  { time: 105, text: "Sitaaron ki mehfil ne karke ishaara" },
  { time: 109, text: "Kahaa ab toh saara jahaan hai tumhaara" },
  { time: 121, text: "Mohabbat jawaan ho, khula aasmaan ho" },
  { time: 125, text: "Kare koyi dil arzu kya" },
  { time: 130, text: "Yeh raaten yeh mausam, nadee ka kinara, ye chanchal hawaa" },
  { time: 145, text: "Kasam hai tumhe, tum agar mujhse ruthe" },
  { time: 153, text: "Rahe saans jab tak, yeh bandhan na toote" },
  { time: 160, text: "Tumhe dil diya hai, yeh waada kiya hai" },
  { time: 167, text: "Sanam main tumhaari rahungi sadaa" },
  { time: 172, text: "Yeh raaten yeh mausam, nadee ka kinara, ye chanchal hawaa" },
  { time: 178, text: "Kahaa do dillon ne, ki milkar kabhi hum na honge jooda" },
  { time: 185, text: "Yeh raaten yeh mausam, nadee ka kinara, ye chanchal hawaa" }
]

  },
  {
    title: "Ilahi",
    artist: "Arijit Singh",
    year: 2013,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063976/Yeh_jawani_hai_deewani_abf25l.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063967/Ilahi_hwcek7.mp3",
    genre: "Soundtrack",
    language: "Hindi",
    bgColor: "#1b2233",
    lyricsBgColor: "#2d3a50",
    lyricsColor: "#79e4ff",
    lyrics: [
  { time: 36.801, text: "Baagi udaan pe hee naa jaane kyun" },
  { time: 42.552, text: "Ilaahi, mera jee aaye-aaye (ooh)" },
  { time: 46.552, text: "Ilaahi, mera jee aaye-aaye (aah)" },
  { time: 65.050, text: "Kal pe savaal hai, jeenaa filhal hai" },
  { time: 73.300, text: "Kaanaa-badoshiyon pe hee jaane kyun" },
  { time: 79.801, text: "Ilaahi mera jee aaye-aaye" },
  { time: 82.550, text: "Ilaahi, mera jee aaye-aaye (ooh)" },
  { time: 116.913, text: "Mera falsafaa, kandhe pe mera bastaa" },
  { time: 120.412, text: "Chalaa main jahaan le chalaa muje rastaa" },
  { time: 124.162, text: "Boondon pe nahin, gahare samundar pe" },
  { time: 127.911, text: "Whoa-ooh, whoa-ooh, whoa-oh" },
  { time: 130.721, text: "Ilaahi, mera jee aaye-aaye (ilaahi, mera jee aaye-aaye)" },
  { time: 134.813, text: "Ilaahi, mera jee aaye-aaye (ilaahi, mera jee aaye-aaye)" },
  { time: 169.084, text: "Shaamein malang see, raatein surang see (ooh)" },
  { time: 176.159, text: "Baagi udaan pe hee naa jaane kyun (aah, ooh)" },
  { time: 181.531, text: "Ilaahi, mera jee aaye-aaye (aah)" },
  { time: 185.031, text: "Ilaahi, mera jee aaye-aaye (ooh)" },
  { time: 190.780, text: "Ooh-aah, ooh-aah" },
  { time: 193.781, text: "Ooh-aah, ooh-aah" },
  { time: 197.281, text: "Ooh-aah, ooh-aah" },
  { time: 201.282, text: "Ooh-aah, ooh-aah, yeah" }
]

  },
  {
    title: "Tum Se Hi",
    artist: "Mohit Chauhan",
    year: 2007,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063976/tum_se_hi_pversl.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063977/Tum_Se_Hi_Jab_vcb2vr.mp3",
    genre: "Romantic",
    language: "Hindi",
    bgColor: "#1e292e",
    lyricsBgColor: "#1e292e",
    lyricsColor: "#f3de3fff",
    lyrics: [
  { time: 29.95, text: "Na hai yeh pana" },
  { time: 36.94, text: "Na Khona hi hai" },
  { time: 43.94, text: "Tera Na hona jane" },
  { time: 52.20, text: "Kyun hona hi hai" },
  { time: 59.69, text: "Tum se hi din hota hai" },
  { time: 63.18, text: "Surmaiye shaam aati" },
  { time: 66.94, text: "Tumse hi tumse hi" },
  { time: 70.44, text: "Har ghari saans aati hai" },
  { time: 74.20, text: "Zindagi kehlati hai" },
  { time: 77.70, text: "Tumse hi tumse hi" },
  { time: 82.44, text: "Na hai yeh pana" },
  { time: 88.95, text: "Na Khona hi hai" },
  { time: 95.72, text: "Tera Na hona jane" },
  { time: 103.68, text: "Kyun hona hi hai" },
  { time: 126.45, text: "Aankhon mein ankhen teri" },
  { time: 130.44, text: "Bahoon mein baahein teri" },
  { time: 133.94, text: "Mera na mujh mein kuch raha hua kya" },
  { time: 140.94, text: "Baaton mein baatein teri" },
  { time: 144.97, text: "Raatein saugatein teri" },
  { time: 148.72, text: "Kyun tera sab yeh ho gaya" },
  { time: 153.68, text: "hua kya" },
  { time: 155.69, text: "Mein kahin bhi jata hoon" },
  { time: 159.19, text: "Tumse hi mil jata hoon" },
  { time: 162.45, text: "Tumse hi tumse hi" },
  { time: 166.72, text: "Shoor mein khamoshi hai" },
  { time: 170.18, text: "Thodi se Behoshi hai" },
  { time: 173.97, text: "Tum se hi tum se hi" },
  { time: 214.94, text: "Aadha sa wada kabhi" },
  { time: 218.69, text: "Aadhe se zayada kabhi" },
  { time: 222.70, text: "Jee chahe karlu is trah wafa ka" },
  { time: 229.70, text: "Chode na chote kabhi" },
  { time: 233.72, text: "Tode na tute kabhi" },
  { time: 238.19, text: "Jo dhaga tumse jud gaya wafa ka" },
  { time: 244.45, text: "Mein Tera sarmaya hoon" },
  { time: 247.96, text: "Jo bhi mein ban paya hoon" },
  { time: 250.97, text: "Tumse hi tumse hi" },
  { time: 255.19, text: "Raste miljate hai" },
  { time: 259.19, text: "Manzile miljati hai" },
  { time: 262.45, text: "Tumse hi tumse hi" },
  { time: 266.94, text: "Na hai yeh pana" },
  { time: 273.69, text: "Na Khona hi hai" },
  { time: 280.71, text: "Tera Na hona jane" },
  { time: 285.18, text: "Kyun hona hi hai" }
]

  },
  {
    title: "Apna Bana Le",
    artist: "Arijit Singh",
    year: 2023,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751097716/apna_bana_le_vyklgi.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751097775/Apna_Bana_Le_spwmof.mp3",
    genre: "Romantic",
    language: "Hindi",
    bgColor: "#1e292e",
    lyricsBgColor: "#2b3b3f",
    lyricsColor: "#c2f5ff",
    lyrics: [
  { time: 22.06, text: "Tu Mera Koyi Na" },
  { time: 24.19, text: "Hoke Bhi Kuchh Laage" },
  { time: 26.84, text: "Tu Mera Koyi Na" },
  { time: 29.23, text: "Hoke Bhi Kuchh Laage" },
  { time: 31.89, text: "Kiya Re Jo Bhi Toone" },
  { time: 33.76, text: "Kaise Kiya Re" },
  { time: 37.22, text: "Jiya Ko Mere Baandh" },
  { time: 39.61, text: "Aise Liya Re" },
  { time: 42.26, text: "Samajh Ke Bhi Na" },
  { time: 44.92, text: "Samajh Main Sakun" },
  { time: 47.57, text: "Saweron Ka Bhi Mere" },
  { time: 49.97, text: "Tu Sooraj Laage" },
  { time: 52.62, text: "Tu Mera Koyi Na" },
  { time: 55.01, text: "Hoke Bhi Kuchh Laage" },
  { time: 57.67, text: "Tu Mera Koyi Na" },
  { time: 60.06, text: "Hoke Bhi Kuchh Laage" },
  { time: 62.72, text: "Tu Mera Koyi Na" },
  { time: 65.11, text: "Hoke Bhi Kuchh Laage" },
  { time: 69.89, text: "Apna Bana Le Piya" },
  { time: 72.02, text: "Apna Bana Le Piya" },
  { time: 74.93, text: "Apna Bana Le Mujhe" },
  { time: 76.80, text: "Apna Bana Le Piya" },
  { time: 80.25, text: "Apna Bana Le Piya" },
  { time: 82.64, text: "Apna Bana Le Piya" },
  { time: 85.03, text: "Dil Ke Nagar Mein" },
  { time: 88.22, text: "Shehar Tu Basa Le Piya" },
  { time: 113.46, text: "Chhoone Se Tere" },
  { time: 115.31, text: "Haan Tere Haan Tere" },
  { time: 120.36, text: "Feeki Ruton Ko Rang Lage" },
  { time: 127.81, text: "Hmm.. Chhoone Se Tere" },
  { time: 130.71, text: "Haan Tere Haan Tere" },
  { time: 133.90, text: "Feeki Ruton Ko Rang Lage" },
  { time: 138.95, text: "Teri Disha Mein Kyun Chalne Se Mere" },
  { time: 144.00, text: "Pairon Ko Pankh Lage" },
  { time: 147.19, text: "Raha Na Mere Kaam Ka Jag Saara" },
  { time: 152.24, text: "Haan Bas Tere Naam Se Hi Guzaara" },
  { time: 157.28, text: "Ulajh Ke Yoon Na" },
  { time: 161.00, text: "Sulajh Na Sakun" },
  { time: 165.25, text: "Zubaaniyan Teri" },
  { time: 167.64, text: "Jhoothi Bhi Sach Laage" },
  { time: 170.03, text: "Tu Mera Koyi Na" },
  { time: 172.42, text: "Hoke Bhi Kuchh Laage" },
  { time: 175.08, text: "Tu Mera Koyi Na" },
  { time: 179.06, text: "Hoke Bhi Kuchh Laage" },
  { time: 180.65, text: "Tu Mera Koyi Na" },
  { time: 183.04, text: "Hoke Bhi Kuchh Laage" },
  { time: 187.29, text: "Apna Bana Le Piya" },
  { time: 189.42, text: "Apna Bana Le Piya" },
  { time: 192.07, text: "Apna Bana Le Mujhe" },
  { time: 194.20, text: "Apna Bana Le Piya" },
  { time: 197.39, text: "Apna Bana Le Piya" },
  { time: 199.51, text: "Apna Bana Le Piya" },
  { time: 202.17, text: "Dil Ke Nagar Mein" },
  { time: 204.29, text: "Shehar Tu Basa Le Piya" },
  { time: 209.34, text: "Ho Sab Kuchh Mera Chahe" },
  { time: 214.12, text: "Naam Apne Likha Le" },
  { time: 219.17, text: "Badle Mein Itni Toh" },
  { time: 224.48, text: "Yaari Nibha Le" },
  { time: 229.53, text: "Jag Ki Hirasat Se" },
  { time: 233.51, text: "Mujhko Chhuda Le" },
  { time: 238.29, text: "Apna Bana Le" },
  { time: 242.28, text: "Bas Apna Bana Le" },
  { time: 248.13, text: "Apna Bana Le" },
  { time: 252.90, text: "Apna Bana Le" }
]

  },
  {
    title: "Kya Mujhe Pyaar Hai",
    artist: "KK",
    year: 2006,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063968/Kya_Mujhe_Pyaar_Hai_p4tnwm.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063970/Kya_Mujhe_Pyaar_Hai_yx8anp.mp3",
    genre: "Soundtrack",
    language: "Hindi",
    bgColor: "#2c1e2e",
    lyricsBgColor: "#2d1f00ff",
    lyricsColor: "#caf3ebff",
    lyrics: [
  { time: 5.29, text: "Tum kyun chale aate ho" },
  { time: 10.94, text: "Har roz in khwaabon mein" },
  { time: 16.24, text: "Chupke se aa bhi jaao" },
  { time: 21.56, text: "Ek din meri baahon mein" },
  { time: 26.61, text: "Tere hi sapne andheron mein, ujaalon mein" },
  { time: 31.92, text: "Koi nasha hai teri aankhon ke pyaalon mein" },
  { time: 37.50, text: "Tu mere khwaabon mein, jawaabon mein, sawaalon mein" },
  { time: 42.80, text: "Har din chura tumhe main laata hoon khayaalon mein" },
  { time: 48.14, text: "Kya mujhe pyaar hai aa" },
  { time: 53.46, text: "Kaisa khumaar hai aa" },
  { time: 59.59, text: "Kya mujhe pyaar hai aa" },
  { time: 65.95, text: "Kaisa khumaar hai aa" },
  { time: 85.95, text: "Patthar ke in raaston pe" },
  { time: 91.01, text: "Phoolon ki ek chaadar hai" },
  { time: 96.34, text: "Jabse mile ho humko" },
  { time: 101.93, text: "Badla har ik manzar hai" },
  { time: 106.99, text: "Dekhun jahan main neele neele aasmaan tale" },
  { time: 112.05, text: "Rang naye naye hain jaise ghulte hue" },
  { time: 117.37, text: "Soye se khwaab mere jaage tere waaste" },
  { time: 122.95, text: "Tere khayaalon se hain bheege mere raaste" },
  { time: 128.26, text: "Kya mujhe pyaar hai aa" },
  { time: 133.57, text: "Kaisa khumaar hai aa" },
  { time: 138.91, text: "Kya mujhe pyaar hai aa" },
  { time: 144.23, text: "Kaisa khumaar hai aa" }
]

  },
  {
    title: "Khuda Jaane",
    artist: "KK, Shilpa Rao",
    year: 2006,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063969/khuda_jaane_bghgrw.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063973/Khuda_Jaane_t1qquy.mp3",
    genre: "Romantic",
    language: "Hindi",
    bgColor: "#19272e",
    lyricsBgColor: "#768a83ff",
    lyricsColor: "#f8f874ff",
    lyrics: [
  { time: 23.43, text: "Sajde Mein Yun Hi Jhukta Hoon" },
  { time: 26.55, text: "Tum Pe Hi Aa Ke Rukhta Hoon" },
  { time: 29.87, text: "Kya Yeh Sab Ko Hota Hai" },
  { time: 32.95, text: "Hum Ko Kya Lena Hai Sab Se" },
  { time: 35.71, text: "Tum Se Hi Sab Baatein Ab Se" },
  { time: 38.75, text: "Ban Gaye Ho Tum Meri Dua" },
  { time: 44.67, text: "Sajde Mein Yun Hi Jhukta Hoon" },
  { time: 47.43, text: "Tum Pe Hi Aa Ke Rukhta Hoon" },
  { time: 50.67, text: "Kya Yeh Sab Ko Hota Hai" },
  { time: 53.83, text: "Hum Ko Kya Lena Hai Sab Se" },
  { time: 56.84, text: "Tum Se Hi Sab Baatein Ab Se" },
  { time: 59.35, text: "Ban Gaye Ho Tum Meri Dua" },
  { time: 64.95, text: "Khuda Jaane Ke Mein Fida Hoon" },
  { time: 70.71, text: "Khuda Jaane Mein Mitt Gaya" },
  { time: 76.47, text: "Khuda Jaane Yeh Kyun Hua Hai" },
  { time: 83.55, text: "Ke Ban Gaye Ho Tum Mere Khuda" },
  { time: 113.91, text: "Tu Kahe To Tere Hi Kadam Ke" },
  { time: 118.07, text: "Main Nishanon Pe" },
  { time: 119.75, text: "Chalun Rukun Ishaare Pe" },
  { time: 125.64, text: "Tu Kahe To Khwabon Ka Bana Ke" },
  { time: 128.71, text: "Main Bahana Sa" },
  { time: 131.79, text: "Mila Karun Sirhaane Pe" },
  { time: 137.72, text: "Ho Tum Pe Dil Ki Baatein Seekhi" },
  { time: 140.78, text: "Tum Se Hi Yeh Raahein Seekhi" },
  { time: 143.55, text: "Tum Pe Mar Ke Main To Jee Gaaya" },
  { time: 148.85, text: "Khuda Jaane Ke Mein Fida Hoon" },
  { time: 154.54, text: "Khuda Jaane Mein Mitt Gaya" },
  { time: 160.94, text: "Khuda Jaane Yeh Kyun Hua Hai" },
  { time: 167.38, text: "Ke Ban Gaye Ho Tum Mere Khuda" },
  { time: 210.23, text: "Dil Kahe Ke Aaj To Chupa Lo Tum" },
  { time: 213.86, text: "Panahon Mein" },
  { time: 215.50, text: "Ke Daar Hai Tum Ko Kha Doonga" },
  { time: 221.62, text: "Dil Kahe Sambhal Zara Khushi Ko" },
  { time: 225.82, text: "Na Nazar Laga" },
  { time: 227.74, text: "Ke Daar Hai Mein To Ro Doonga" },
  { time: 232.84, text: "O Karti Hoon Sau Vaade Tum Se" },
  { time: 236.66, text: "Baandhe Dil Ke Dhaage Tum Se" },
  { time: 239.46, text: "Yeh Tumhe Na Jaane Kya Hua" },
  { time: 244.78, text: "Khuda Jaane Ke Mein Fida Hoon" },
  { time: 250.90, text: "Khuda Jaane Mein Mitt Gaya" },
  { time: 256.73, text: "Khuda Jaane Yeh Kyun Hua Hai" },
  { time: 262.78, text: "Ke Ban Gaye Ho Tum Mere Khuda" },
  { time: 270.18, text: "Sajde Mein Yun Hi Jhukta Hoon" },
  { time: 272.94, text: "Tum Pe Hi Aa Ke Rukhta Hoon" },
  { time: 275.94, text: "Kya Yeh Sab Ko Hota Hai" },
  { time: 278.70, text: "Hum Ko Kya Lena Hai Sab Se" },
  { time: 281.81, text: "Tum Se Hi Sab Baatein Ab Se" },
  { time: 284.83, text: "Ban Gaye Ho Tum Meri Dua" },
  { time: 290.34, text: "Khuda Jaane Ke Mein Fida Hoon" },
  { time: 295.82, text: "Khuda Jaane Mein Mitt Gaya" },
  { time: 302.22, text: "Khuda Jaane Yeh Kyun Hua Hai" },
  { time: 308.11, text: "Ke Ban Gaye Ho Tum Mere Khuda" },
  { time: 315.02, text: "Ke Ban Gaye Ho Tum Mere Khuda" }
]

    
  },
  // Punjabi
  {
    title: "Illegal Weapon",
    artist: "Jasmine Sandlas, Garry Sandhu",
    year: 2015,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063967/Illegal-Weaponjpg_uaycls.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063968/Illegal_Weapon_vitegh.mp3",
    genre: "Dance",
    language: "Punjabi",
    bgColor: "#301a1c",
    lyricsBgColor: "#3c2325",
    lyricsColor: "#ff5c5c",
    lyrics : [
  { time: 0.00, text: "Ankh surme naa laddi hoi naar di" },
  { time: 19.00, text: "Khinch khinch ke nishane sidhe maardi" },
  { time: 30.00, text: "Meri thori bohti daaru aaj lagi sohnea" },
  { time: 34.00, text: "Tahiyon gora mukh hoya angyaar warga" },
  { time: 38.00, text: "Mundeya nu sooli utte tangi rakhda" },
  { time: 41.00, text: "Bai mera nakhra jo teekhi talwar warga" },
  { time: 61.00, text: "Muchhan khundiyan karaiyan tere karke" },
  { time: 63.00, text: "High court vich chalde ne parche" },
  { time: 71.00, text: "Khake makhan malaiyan hoya wadda balliye" },
  { time: 76.00, text: "Taiyon rob rakhan filmy star warga" },
  { time: 79.00, text: "Kudiyan de seene vich thaa wajda" },
  { time: 81.00, text: "Bai munda UP de najaij hathyaar warga" },
  { time: 102.00, text: "Meri gall-baat end jatti lit haaniya" },
  { time: 105.00, text: "Main jaavan do time gym poori fit haaniya" },
  { time: 112.00, text: "Ho jidron vi langhan mere hon charche" },
  { time: 115.00, text: "Meri natural beauty kare hit haaniya" },
  { time: 122.00, text: "Tere je likhari Garry chatti firde" },
  { time: 125.00, text: "Tere je likhari Sandhu chatti firde" },
  { time: 127.00, text: "Munda labhna main Shiv di kitaab warga" },
  { time: 130.00, text: "Mundeya nu sooli utte tangi rakhda" },
  { time: 133.00, text: "Bai mera nakhra jo teekhi talwar warga" },
  { time: 152.00, text: "Mere kurte pajame diyan fan goriyan" },
  { time: 156.00, text: "Mari jandiyan Canada diyan tan choriyan" },
  { time: 163.00, text: "Ho jiven gudd piche makhiya da jhund firda" },
  { time: 166.00, text: "Aiven ghumdiya piche ganne diyan boriyan" },
  { time: 173.00, text: "Honi kisse naal ajj koi thaggi lagdi" },
  { time: 178.00, text: "Hun baneya mahaul ji shikaar warga" },
  { time: 181.00, text: "Kudiyan de seene vich thaa wajda" },
  { time: 183.00, text: "Bai munda UP de najaij hathyaar warga" },
  { time: 197.00, text: "Kudiyan de seene vich thaa wajda, ve munda UP de najaij hathyaar warga" }
]


  },
  {
    title: "Na Ja",
    artist: "Pav Dharia",
    year: 2017,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063970/na_ja_gqkx9f.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063973/Na_Ja_jcybmx.mp3",
    genre: "Pop",
    language: "Punjabi",
    bgColor: "#201f26",
    lyricsBgColor: "#2b2a33",
    lyricsColor: "#c2a2ff",
    lyrics: [
  { time: 4.52, text: "Na ja na ja na ja" },
  { time: 9.51, text: "Ni kudi ae tu alright" },
  { time: 11.77, text: "Aaja ni re I won't bite" },
  { time: 14.77, text: "Lage tu mainu sexy" },
  { time: 17.28, text: "Tahi main jaaga all night" },
  { time: 20.52, text: "Karavengi tu murder" },
  { time: 22.76, text: "Ho bhavein hove daylight" },
  { time: 25.29, text: "Jhakas teri body" },
  { time: 27.75, text: "I fell in love at first sight" },
  { time: 31.04, text: "Kuwari ae ton soniye" },
  { time: 32.51, text: "Te main vi ae kuwara" },
  { time: 33.77, text: "Chad'di jawani hun lutt le nazara" },
  { time: 36.51, text: "Je na mainu karti ni puchhna dobara" },
  { time: 38.27, text: "Pher rotiyan pakayi" },
  { time: 40.26, text: "Naale mere gaane gayi" },
  { time: 41.77, text: "Na ja na ja na ja na ja" },
  { time: 43.02, text: "Mittran ton door" },
  { time: 44.54, text: "Ambran ton aayi tu lagdi ae hoor" },
  { time: 47.02, text: "Att tera nakhra tera ki kasoor" },
  { time: 49.79, text: "Mainu ni pasand tu kardi zaroor" },
  { time: 51.79, text: "Mainu ni pasand tu kardi zaroor" }, // duplicate for x2
  { time: 63.04, text: "Na ja na ja na ja" },
  { time: 64.54, text: "Na ja na ja na ja" },
  { time: 66.04, text: "Na ja na ja na ja" },
  { time: 67.54, text: "Na ja na ja na ja" },
  { time: 73.78, text: "Sohni badi lagdi ae" },
  { time: 75.75, text: "Jad kurti bhavein kaale rang di" },
  { time: 79.03, text: "Thoda je mere nerhe aa" },
  { time: 82.25, text: "Tere utte aa lagda nazar ae sab di" },
  { time: 84.52, text: "Lak tera hilda ae" },
  { time: 86.27, text: "Jiven paani de vich hildi supni" },
  { time: 89.50, text: "Tu ajj mainu roki na" },
  { time: 91.77, text: "Tere kolon haan kara ke chad ni" },
  { time: 95.05, text: "Kuwari ae ton soniye" },
  { time: 96.29, text: "Te main vi ae kuwara" },
  { time: 97.76, text: "Chad'di jawani hun lutt le nazara" },
  { time: 100.28, text: "Je na mainu karti ni puchhna dobara" },
  { time: 103.01, text: "Pher rotiyan pakayi" },
  { time: 104.28, text: "Naale mere gaane gayi" },
  { time: 105.77, text: "Na ja na ja na ja na ja" },
  { time: 107.27, text: "Mittran ton door" },
  { time: 108.53, text: "Ambran ton aayi tu lagdi ae hoor" },
  { time: 111.02, text: "Att tera nakhra tera ki kasoor" },
  { time: 113.77, text: "Mainu ni pasand tu kardi zaroor" },
  { time: 115.77, text: "Mainu ni pasand tu kardi zaroor" }, // duplicate for x2
  { time: 129.29, text: "Girl you look so good" },
  { time: 130.51, text: "Teriyan nigahwan mainu maar sutteya ae" },
  { time: 133.75, text: "When you walk my way" },
  { time: 135.74, text: "Teriyan adavan mera dil lutteya ae" },
  { time: 139.55, text: "When you shake them heels" },
  { time: 141.26, text: "Tere piche lag ke main chadte saare" },
  { time: 144.77, text: "Make me go crazy.." },
  { time: 148.80, text: "You talk and I am watching" },
  { time: 150.02, text: "I like how you talk" },
  { time: 151.27, text: "Mesmerized by you I don't want you to stop" },
  { time: 153.75, text: "Baby just tell 'em you writing for me" },
  { time: 156.79, text: "Give you the word" },
  { time: 157.51, text: "And I won't charge you a fee" },
  { time: 159.27, text: "Take you to Paris" },
  { time: 160.52, text: "I'll take you to London" },
  { time: 161.77, text: "Five star hotel food" },
  { time: 163.03, text: "That you couldn't imagine" },
  { time: 164.77, text: "Playback your dreams Baby" },
  { time: 166.02, text: "I could just fund it" },
  { time: 167.02, text: "Long as you with me" },
  { time: 168.51, text: "You'll live in abundance" },
  { time: 170.04, text: "Kuwari ae ton soniye" },
  { time: 171.25, text: "Te main vi ae kuwara" },
  { time: 172.51, text: "Chad'di jawani hun lutt le nazara" },
  { time: 175.04, text: "Je na mainu karti ni puchhna dobara" },
  { time: 177.53, text: "Pher rotiyan pakayi" },
  { time: 179.01, text: "Naale mere gaane gayi" },
  { time: 180.27, text: "Na ja na ja na ja na ja" },
  { time: 181.76, text: "Mittran ton door" },
  { time: 183.28, text: "Ambran ton aayi tu lagdi ae hoor" },
  { time: 185.76, text: "Att tera nakhra tera ki kasoor" },
  { time: 188.27, text: "Mainu ni pasand tu kardi zaroor" },
  { time: 190.27, text: "Mainu ni pasand tu kardi zaroor" } // duplicate for x2
]

  },
  {
    title: "Saakhiyan",
    artist: "Maninder Buttar",
    year: 2017,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063974/sakhiiyan_wy4fnr.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063975/Sakhiyaan_fbafsi.mp3",
    genre: "Pop",
    language: "Punjabi",
     bgColor: "#211f2b",
    lyricsBgColor: "#2d2b3a",
    lyricsColor: "#ffc9ec",
    lyrics: [
  { time: 0.07, text: "Oyo aa" },
  { time: 5.52, text: "Oyo aa" },
  { time: 11.80, text: "Sakhiyaan ne mainu maine maardiyan" },
  { time: 14.79, text: "Uddiyan ne channa gallan pyar diyan" },
  { time: 17.58, text: "Sham nu kithe kihde nal huna ae" },
  { time: 20.54, text: "Vekhiyan ve photoan main car diyan" },
  { time: 23.29, text: "Mainu dar jeya lagda ae dil tutt na jaye vichara" },
  { time: 29.03, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 34.55, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 40.30, text: "Na na na na…" },
  { time: 45.80, text: "Ta na na na na…" },
  { time: 52.28, text: "Jadon kali behni aa khayal eh sataunde ne bahar jaake sunn da ae phone kihde aunde ne phone kihde aunde ne" },
  { time: 61.04, text: "Jadon kali behni aa khayal eh sataunde ne bahar jaake sunn da ae phone kihde aunde ne" },
  { time: 66.78, text: "Kari na please aesi gal kise nal aj kise nal ne jo kal kise nal" },
  { time: 72.54, text: "Tere nal hona ae guzara jatti da mera nahiyo hor koi hal kise nal" },
  { time: 78.04, text: "Tun jihde ton roke main kamm na kara dubara" },
  { time: 83.81, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 89.54, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 95.56, text: "Oyo aa" },
  { time: 101.29, text: "Oyo aa" },
  { time: 107.04, text: "Ehna sochi tenu mutiyaran ton ni rokdi theek hai na bas tere yaaran ton ni rokdi yaaran ton ni rokdi" },
  { time: 116.29, text: "Ehna sochi tenu mutiyaran ton ni rokdi theek hai na bas tere yaaran ton ni rokdi" },
  { time: 123.29, text: "Kade mainu filma dikha deya kar kade kade mainu vi ghuma leya kar" },
  { time: 127.57, text: "Saare saal vichon je main russan 1 vaar ehna k ta bann da mana leya kar" },
  { time: 133.02, text: "1 paase tun babbu 1 paase ae jag saara" },
  { time: 138.79, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 144.55, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 150.54, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 156.29, text: "Tere yaar bathere ne mera tun hi bas yaara" },
  { time: 161.54, text: "Na na na na…" },
  { time: 167.29, text: "Ta na na na na…" },
  { time: 173.79, text: "Oyo aa" }
]

  },
  {
    title: "Hass Hass",
    artist: "Diljit Dosanjh, Sia",
    year: 2023,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063966/hass_hass_fo2wxe.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063969/Hass_Hass_t6wczi.mp3",
    genre: "Dance",
    language: "Punjabi",
    bgColor: "#1e202b",
    lyricsBgColor: "#6f0479ff",
    lyricsColor: "#6bc51cff",
    lyrics: [
  { time: 0.34, text: "Oh, I'm gon' take your breath away" },
  { time: 5.51, text: "But don't stop runnin' to me" },
  { time: 11.53, text: "Feel me, and the breeze baby" },
  { time: 13.66, text: "I'm the ocean, sky in heels, baby-baby" },
  { time: 16.75, text: "I'm the forest and the trees, baby" },
  { time: 18.85, text: "You're the Royce and I'm the wheels, baby-baby" },
  { time: 21.71, text: "Tera vi aa dil sab jaan da" },
  { time: 24.46, text: "Tuun jo mili jaappe koi haan da" },
  { time: 27.00, text: "Laal hoya rang asmaan da" },
  { time: 29.69, text: "Roop jiwein nikhri rakhaan da" },
  { time: 32.26, text: "Jithe-jithe jaavein pair rakhdi" },
  { time: 34.88, text: "Sohniye baraf vaangu tharre gabbroo" },
  { time: 37.58, text: "Mang lai je dil laina chauni ain" },
  { time: 40.22, text: "Hass-hass sooli utte chadhde gabbroo" },
  { time: 42.82, text: "Mang lai je dil laina chauni ain" },
  { time: 45.47, text: "Hass-hass sooli utte chadhde gabbroo" },
  { time: 47.86, text: "Oh, I'm gon' take your breath away" },
  { time: 52.94, text: "But don't stop runnin' to me" },
  { time: 58.26, text: "'Cause I will hold you, baby" },
  { time: 63.71, text: "If you're my ocean, I'm your wave" },
  { time: 69.36, text: "Beach utte hathan vich wine ni" },
  { time: 71.88, text: "Hove dovein paase ikko rhyme ni" },
  { time: 74.16, text: "Oh, roop tera dhoop 'ch na khurjey" },
  { time: 77.15, text: "Dand aa pataase kare shine ni" },
  { time: 79.73, text: "Bajwe di hoja dubb jaaniye" },
  { time: 82.44, text: "Athre dosaanjhaale saare gabbroo" },
  { time: 85.10, text: "Mang lai je dil laina chauni ain" },
  { time: 87.88, text: "Hass-hass sooli utte chadhde gabbroo" },
  { time: 90.15, text: "Mang lai je dil laina chauni ain" },
  { time: 92.90, text: "Hass-hass sooli utte chadhde gabbroo" },
  { time: 95.33, text: "Oh, I'm gon' take your breath away" },
  { time: 100.48, text: "But don't stop runnin' to me" },
  { time: 105.61, text: "'Cause I will hold you, baby" },
  { time: 111.06, text: "If you're my ocean, I'm your wave" },
  { time: 116.55, text: "Mang lai je dil laina chauni ain" },
  { time: 119.26, text: "Hass-hass sooli utte chadhde gabbroo" },
  { time: 121.83, text: "Mang lai je dil laina chauni ain" },
  { time: 124.55, text: "Hass-hass sooli utte chadhde gabbroo" },
  { time: 127.94, text: "Dil tainu de ditta main taan sohnia" },
  { time: 132.92, text: "Jaan tere kadman 'ch rakhi hoi ae" },
  { time: 138.44, text: "Marna main teriyan baahaan 'ch chann ve" },
  { time: 143.21, text: "Sohn tere pyaar di main chakki hoi ae" }
]

    
  },
  {
    title: "Naina",
    artist: "Diljit Dosanjh ft. Badshah",
    year: 2024,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063970/naina_vaeagz.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063972/Naina_as1i8k.mp3",
    genre: "Pop",
    language: "Punjabi",
    bgColor: "#1f1a2e",
    lyricsBgColor: "#74660aff",
    lyricsColor: "#030847ff",
    lyrics: [
  { time: 9, text: "Oh rutheya khuda khuda maine liya liya" },
  { time: 12, text: "Tera naam hazaaran baari" },
  { time: 16, text: "Dil mera hua tera tu nasha nasha" },
  { time: 19, text: "Ni mai jaan tere to vaari" },
  { time: 24, text: "Meri khud se badi doori, bas teri hai jee hazoori" },
  { time: 28, text: "Zamaana kya hi samjhega, dil gawana kyun zaroori" },
  { time: 30, text: "Naina da kehna, ni asi tera mukhda dekhte rehna ni" },
  { time: 38, text: "Tu te meri hai na, ishq de ittar rooh ton lehna ni" },
  { time: 43, text: "Naina da kehna, ni asi tera mukhda dekhte rehna ni" },
  { time: 48, text: "Tu te meri hai na, ishq de ittar rooh ton lehna ni" },
  { time: 57, text: "Paaji main kya keh raha tha, ki tere aage kya hi farmaaye" },
  { time: 61, text: "Banke nasha tu ek sar chadh jaye, bas fir tu hi udaye tu hi giraye" },
  { time: 65, text: "Kholke rakhde tu meri third eye" },
  { time: 68, text: "Kaise kahun kya main karun feel" },
  { time: 71, text: "Tujhe nahi pata ke tu kare mujhe heal" },
  { time: 75, text: "Mujhe jab hath lagaye, paas tu aaye" },
  { time: 78, text: "Mera sar ghoome aisa kya hi kardu main" },
  { time: 80, text: "Baby you're a mood mood mood" },
  { time: 82, text: "Baby you're a vibe vibe vibe" },
  { time: 86, text: "Uski adaayein dayein bayein, kaise samjhaayein haye haye" },
  { time: 91, text: "You could bring your crew crew crew, take it to the sky sky sky" },
  { time: 96, text: "Jo na karna chahun, mujhse to wo hi karaaye haye" },
  { time: 101, text: "Naina da kehna, ni asi tera mukhda dekhte rehna ni" },
  { time: 105, text: "Tu te meri hai na, ishq de ittar rooh ton lehna ni" },
  { time: 109, text: "Oh aaj tu bata de mujhe sab soniye" },
  { time: 112, text: "Dinner pe leke chalu kab soniye" },
  { time: 115, text: "Patli kamar baby mai tera lover baby" },
  { time: 118, text: "Mujhse bachale tuhhe rabb soniye" },
  { time: 122, text: "Tujhko pata hai nasha hai, ishq wala hai soniye" },
  { time: 125, text: "Mujhko hua hai saza hai, thoda maza hai soniye" },
  { time: 128, text: "Tera hoke mar jaawani, mai ki jag toh lehna ni" },
  { time: 132, text: "Naina da kehna, ni asi tera mukhda dekhte rehna ni" },
  { time: 136, text: "Tu te meri hai na, ishq de ittar rooh ton lehna ni" },
  { time: 140, text: "Naina da kehna, ni asi tera mukhda dekhte rehna ni" },
  { time: 144, text: "Tu te meri hai na, ishq de ittar rooh ton lehna ni" },
  { time: 148, text: "Naina da kehna" },
  { time: 152, text: "Naina da kehna" }
]


    },
  {
    title: "Pasoori",
    artist: "Shae Gill, Ali Sethi",
    year: 2022,
    coverUrl: "https://res.cloudinary.com/dff38ziqd/image/upload/v1751063972/pasoori_fevwhc.jpg",
    audioUrl: "https://res.cloudinary.com/dff38ziqd/video/upload/v1751063973/Pasoori_mg0rgg.mp3",
    genre: "Fusion",
    language: "Punjabi",
    bgColor: "#1e1e2e",
    lyricsBgColor: "#7c5d01ff",
    lyricsColor: "#940d0dff",
    lyrics: [
  { time: 5.55, text: "Agg lavan majboori nu" },
  { time: 7.93, text: "Aan jaan di pasoori nu" },
  { time: 10.34, text: "Zehar bane haa teri" },
  { time: 13.05, text: "Pee javan main poori nu" },
  { time: 15.70, text: "Aana si oh nai aaya" },
  { time: 18.12, text: "Dil baang baang mera takraya" },
  { time: 20.78, text: "Kaga bol ke das jaavein" },
  { time: 23.48, text: "Pavan gheyo dee choori nu" },
  { time: 26.15, text: "Raawaan ch baawan ch oh nu lukawaan" },
  { time: 28.54, text: "Koi mainu naa roke" },
  { time: 31.20, text: "Mere dhol judaiyan di" },
  { time: 33.59, text: "Tainu khabar kivein hove" },
  { time: 36.25, text: "Aa jaave dil tera" },
  { time: 38.90, text: "Pura vi na hove" },
  { time: 41.56, text: "Haan baniyan banaiyan di" },
  { time: 43.95, text: "Gall baat kivein hove" },
  { time: 46.87, text: "Aa jaave dil tera" },
  { time: 49.26, text: "Pura vi na hove" },
  { time: 55.10, text: "Bhool gayi majboori nu" },
  { time: 57.50, text: "Duniya di dastoori nu" },
  { time: 60.15, text: "Saath tera hai bathera" },
  { time: 62.83, text: "Poora kar zaroori nu" },
  { time: 65.51, text: "Aana si oh nai aaya" },
  { time: 67.89, text: "Raasta naa dikhlaaya" },
  { time: 70.58, text: "Dil humara de sahara" },
  { time: 73.23, text: "Khaahishaat adhuri nu" },
  { time: 75.64, text: "Waari main jaavan" },
  { time: 76.97, text: "Main tainu bulavaan" },
  { time: 78.35, text: "Gall saari tan hove" },
  { time: 80.45, text: "Mere dhol judaiyan di" },
  { time: 83.13, text: "Tenu khabar kivein hove" },
  { time: 85.82, text: "Aa jaave dil tera" },
  { time: 88.21, text: "Poora vi naa hove" },
  { time: 90.90, text: "Haan baniyan banaiyan di" },
  { time: 93.57, text: "Gall baat kivein hove" },
  { time: 96.23, text: "Aa jaave dil tera" },
  { time: 98.89, text: "Poora vi naa hove" },
  { time: 111.93, text: "Mere dhol judaiyan di" },
  { time: 114.37, text: "Sardaari na hove" },
  { time: 117.33, text: "Mere dhol judaiyan di" },
  { time: 122.11, text: "Ahhhhaaaaaaa" },
  { time: 132.73, text: "Mere dhol judaiyaan di, sardaari naa hove" },
  { time: 138.36, text: "Dildaaran di, sab yaaaran di, aazaari naa hove" },
  { time: 143.13, text: "Dildaaran di, sab yaaaran di, aazaari naa hove" },
  { time: 148.73, text: "Aa chalein le ke tujhe" },
  { time: 154.05, text: "Hai jahaan silsilay" },
  { time: 159.10, text: "Tu hai wahi, hai teri kami" },
  { time: 164.14, text: "Bana de, saaja de, panah de hume" },
  { time: 169.19, text: "Bana de, saaja de, panah de hume" },
  { time: 177.43, text: "Agg lavan majboori nu" },
  { time: 179.83, text: "Aan jaan di pasoori nu" },
  { time: 182.74, text: "Zehar bane haan teri" },
  { time: 185.13, text: "Pee jaavan main poori nu" },
  { time: 187.85, text: "Raawaan ch baawan ch oh nu lukawaan" },
  { time: 189.98, text: "Koi mainu na roke" },
  { time: 192.67, text: "Mere dhol judaiyan di" },
  { time: 195.33, text: "Tainu khabar kivein hove" },
  { time: 197.98, text: "Aa jaave dil tera" },
  { time: 200.37, text: "Poora vi naa hove" },
  { time: 203.29, text: "Haan baniyan banaiyan di" },
  { time: 205.69, text: "Gall baat kivein hove" },
  { time: 208.39, text: "Aa jaave dil tera" },
  { time: 211.04, text: "Poora vi naa hove" },
  { time: 213.70, text: "Poora vi naa hove" },
  { time: 216.35, text: "Poora vi naa hove" }
]

  }
];

module.exports={data:songData}
